name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Change directory and run a command
        run: |
          cd apps/web
      - name: Install Playwright Browsers
        run: pnpm --filter buergergeldrechner exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter buergergeldrechner exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
